version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for hot-reload
      - ./api:/app/api
      - ./tests:/app/tests
      - ./pyproject.toml:/app/pyproject.toml
    environment:
      # Development environment variables
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - PYTHONPATH=/app
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Restart policy
    restart: unless-stopped

  # Redis for development (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data: 